id: vaporwave
name: Vaporwave
version: 2.0.0
source: companion
seed: "#180028"
font_family: Lato
day:
  background: "#fffff7fc"
  error: "#ffba1a1a"
  error-container: "#ffffdad6"
  inverse-on-surface: "#fffaedfb"
  inverse-primary: "#ffe6b4ff"
  inverse-surface: "#ff352e38"
  on-background: "#ff201923"
  on-error: "#ffffffff"
  on-error-container: "#ff93000a"
  on-primary: "#ffffffff"
  on-primary-container: "#ff7100a6"
  on-secondary: "#ffffffff"
  on-secondary-container: "#ff593d59"
  on-surface: "#ff201923"
  on-surface-variant: "#ff4d4351"
  on-tertiary: "#ffffffff"
  on-tertiary-container: "#ff653758"
  outline: "#ff7f7382"
  outline-variant: "#ffd0c2d3"
  primary: "#ff9400d8"
  primary-container: "#fff5d9ff"
  secondary: "#ff725572"
  secondary-container: "#fffdd7fa"
  surface: "#fffff7fc"
  surface-bright: "#fffff7fc"
  surface-container: "#fff7eaf8"
  surface-container-high: "#fff1e4f2"
  surface-container-highest: "#ffecdeec"
  surface-container-low: "#fffdeffe"
  surface-container-lowest: "#ffffffff"
  surface-dim: "#ffe3d6e4"
  surface-variant: "#ffeddeef"
  tertiary: "#ff804e70"
  tertiary-container: "#ffffd7ee"
night:
  background: "#ff17111a"
  error: "#ffffb4ab"
  error-container: "#ff93000a"
  inverse-on-surface: "#ff352e38"
  inverse-primary: "#ff9400d8"
  inverse-surface: "#ffecdeec"
  on-background: "#ffecdeec"
  on-error: "#ff690005"
  on-error-container: "#ffffdad6"
  on-primary: "#ff4f0077"
  on-primary-container: "#fff5d9ff"
  on-secondary: "#ff412742"
  on-secondary-container: "#fffdd7fa"
  on-surface: "#ffecdeec"
  on-surface-variant: "#ffd0c2d3"
  on-tertiary: "#ff4c2140"
  on-tertiary-container: "#ffffd7ee"
  outline: "#ff998d9c"
  outline-variant: "#ff4d4351"
  primary: "#ffe6b4ff"
  primary-container: "#ff7100a6"
  secondary: "#ffe0bbdd"
  secondary-container: "#ff593d59"
  surface: "#ff17111a"
  surface-bright: "#ff3e3641"
  surface-container: "#ff241d27"
  surface-container-high: "#ff2f2732"
  surface-container-highest: "#ff3a323d"
  surface-container-low: "#ff201923"
  surface-container-lowest: "#ff120c15"
  surface-dim: "#ff17111a"
  surface-variant: "#ff4d4351"
  tertiary: "#fff2b4db"
  tertiary-container: "#ff653758"