id: black
name: Black
version: 2.0.0
source: companion
seed: "#808078"
font_family: Lato
day:
  background: "#fff9f9f9"
  error: "#ffba1a1a"
  error-container: "#ffffdad6"
  inverse-on-surface: "#fff1f1f1"
  inverse-primary: "#ffc6c6c6"
  inverse-surface: "#ff303030"
  on-background: "#ff1b1b1b"
  on-error: "#ffffffff"
  on-error-container: "#ff410002"
  on-primary: "#ffe2e2e2"
  on-primary-container: "#ffffffff"
  on-secondary: "#ffffffff"
  on-secondary-container: "#ff1b1b1b"
  on-surface: "#ff1b1b1b"
  on-surface-variant: "#ff474747"
  on-tertiary: "#ffe2e2e2"
  on-tertiary-container: "#ffffffff"
  outline: "#ff777777"
  outline-variant: "#ffc6c6c6"
  primary: "#ff000000"
  primary-container: "#ff3b3b3b"
  secondary: "#ff5e5e5e"
  secondary-container: "#ffd4d4d4"
  surface: "#fff9f9f9"
  surface-bright: "#fff9f9f9"
  surface-container: "#ffeeeeee"
  surface-container-high: "#ffe8e8e8"
  surface-container-highest: "#ffe2e2e2"
  surface-container-low: "#fff3f3f3"
  surface-container-lowest: "#ffffffff"
  surface-dim: "#ffdadada"
  surface-variant: "#ffe2e2e2"
  tertiary: "#ff3b3b3b"
  tertiary-container: "#ff747474"
night:
  background: "#ff131313"
  error: "#ffffb4ab"
  error-container: "#ff93000a"
  inverse-on-surface: "#ff303030"
  inverse-primary: "#ff5e5e5e"
  inverse-surface: "#ffe2e2e2"
  on-background: "#ffe2e2e2"
  on-error: "#ff690005"
  on-error-container: "#ffffdad6"
  on-primary: "#ff1b1b1b"
  on-primary-container: "#ff000000"
  on-secondary: "#ff1b1b1b"
  on-secondary-container: "#ffe2e2e2"
  on-surface: "#ffe2e2e2"
  on-surface-variant: "#ffc6c6c6"
  on-tertiary: "#ff1b1b1b"
  on-tertiary-container: "#ff000000"
  outline: "#ff919191"
  outline-variant: "#ff474747"
  primary: "#ffffffff"
  primary-container: "#ffd4d4d4"
  secondary: "#ffc6c6c6"
  secondary-container: "#ff474747"
  surface: "#ff131313"
  surface-bright: "#ff393939"
  surface-container: "#ff1f1f1f"
  surface-container-high: "#ff2a2a2a"
  surface-container-highest: "#ff353535"
  surface-container-low: "#ff1b1b1b"
  surface-container-lowest: "#ff0e0e0e"
  surface-dim: "#ff131313"
  surface-variant: "#ff474747"
  tertiary: "#ffe2e2e2"
  tertiary-container: "#ff919191"