id: waves
name: Waves
version: 2.0.0
source: companion
seed: "#308888"
font_family: Lato
day:
  background: "#ffeefcfb"
  error: "#ffba1a1a"
  error-container: "#ffffdad6"
  inverse-on-surface: "#ffe5f4f3"
  inverse-primary: "#ff00dddd"
  inverse-surface: "#ff263333"
  on-background: "#ff111e1e"
  on-error: "#ffffffff"
  on-error-container: "#ff93000a"
  on-primary: "#ffffffff"
  on-primary-container: "#ff004f50"
  on-secondary: "#ffffffff"
  on-secondary-container: "#ff204d56"
  on-surface: "#ff111e1e"
  on-surface-variant: "#ff394a4a"
  on-tertiary: "#ffffffff"
  on-tertiary-container: "#ff044d66"
  outline: "#ff697a7a"
  outline-variant: "#ffb8cac9"
  primary: "#ff006a6a"
  primary-container: "#ff00fbfc"
  secondary: "#ff3a656e"
  secondary-container: "#ffbeeaf5"
  surface: "#ffeefcfb"
  surface-bright: "#ffeefcfb"
  surface-container: "#ffe2f1f0"
  surface-container-high: "#ffddebea"
  surface-container-highest: "#ffd7e5e5"
  surface-container-low: "#ffe8f7f6"
  surface-container-lowest: "#ffffffff"
  surface-dim: "#ffcedddc"
  surface-variant: "#ffd3e6e5"
  tertiary: "#ff2a657f"
  tertiary-container: "#ffc1e8ff"
night:
  background: "#ff091515"
  error: "#ffffb4ab"
  error-container: "#ff93000a"
  inverse-on-surface: "#ff263333"
  inverse-primary: "#ff006a6a"
  inverse-surface: "#ffd7e5e5"
  on-background: "#ffd7e5e5"
  on-error: "#ff690005"
  on-error-container: "#ffffdad6"
  on-primary: "#ff003737"
  on-primary-container: "#ff00fbfc"
  on-secondary: "#ff01363f"
  on-secondary-container: "#ffbeeaf5"
  on-surface: "#ffd7e5e5"
  on-surface-variant: "#ffb8cac9"
  on-tertiary: "#ff003548"
  on-tertiary-container: "#ffc1e8ff"
  outline: "#ff829494"
  outline-variant: "#ff394a4a"
  primary: "#ff00dddd"
  primary-container: "#ff004f50"
  secondary: "#ffa2ced9"
  secondary-container: "#ff204d56"
  surface: "#ff091515"
  surface-bright: "#ff2f3c3b"
  surface-container: "#ff152222"
  surface-container-high: "#ff1f2c2c"
  surface-container-highest: "#ff2a3737"
  surface-container-low: "#ff111e1e"
  surface-container-lowest: "#ff041010"
  surface-dim: "#ff091515"
  surface-variant: "#ff394a4a"
  tertiary: "#ff97ceec"
  tertiary-container: "#ff044d66"