id: retro
name: Retro
version: 2.0.0
source: companion
seed: "#688090"
font_family: Lato
day:
  background: "#fff5faff"
  error: "#ffba1a1a"
  error-container: "#ffffdad6"
  inverse-on-surface: "#ffe8f2fa"
  inverse-primary: "#ff7ed0ff"
  inverse-surface: "#ff283238"
  on-background: "#ff131d23"
  on-error: "#ffffffff"
  on-error-container: "#ff93000a"
  on-primary: "#ffffffff"
  on-primary-container: "#ff004c6a"
  on-secondary: "#ffffffff"
  on-secondary-container: "#ff324862"
  on-surface: "#ff131d23"
  on-surface-variant: "#ff3c4851"
  on-tertiary: "#ffffffff"
  on-tertiary-container: "#ff354571"
  outline: "#ff6c7982"
  outline-variant: "#ffbbc8d2"
  primary: "#ff00658b"
  primary-container: "#ffc5e7ff"
  secondary: "#ff4a607b"
  secondary-container: "#ffd1e4ff"
  surface: "#fff5faff"
  surface-bright: "#fff5faff"
  surface-container: "#ffe5eff8"
  surface-container-high: "#ffe0e9f2"
  surface-container-highest: "#ffdae4ec"
  surface-container-low: "#ffebf5fd"
  surface-container-lowest: "#ffffffff"
  surface-dim: "#ffd1dbe4"
  surface-variant: "#ffd7e4ef"
  tertiary: "#ff4d5d8b"
  tertiary-container: "#ffdae2ff"
night:
  background: "#ff0b151a"
  error: "#ffffb4ab"
  error-container: "#ff93000a"
  inverse-on-surface: "#ff283238"
  inverse-primary: "#ff00658b"
  inverse-surface: "#ffdae4ec"
  on-background: "#ffdae4ec"
  on-error: "#ff690005"
  on-error-container: "#ffffdad6"
  on-primary: "#ff00344a"
  on-primary-container: "#ffc5e7ff"
  on-secondary: "#ff1a324b"
  on-secondary-container: "#ffd1e4ff"
  on-surface: "#ffdae4ec"
  on-surface-variant: "#ffbbc8d2"
  on-tertiary: "#ff1d2f59"
  on-tertiary-container: "#ffdae2ff"
  outline: "#ff86929c"
  outline-variant: "#ff3c4851"
  primary: "#ff7ed0ff"
  primary-container: "#ff004c6a"
  secondary: "#ffb1c8e8"
  secondary-container: "#ff324862"
  surface: "#ff0b151a"
  surface-bright: "#ff313a41"
  surface-container: "#ff172127"
  surface-container-high: "#ff222b31"
  surface-container-highest: "#ff2d363c"
  surface-container-low: "#ff131d23"
  surface-container-lowest: "#ff060f15"
  surface-dim: "#ff0b151a"
  surface-variant: "#ff3c4851"
  tertiary: "#ffb5c5f9"
  tertiary-container: "#ff354571"