id: squares
name: Squares
version: 2.0.0
source: companion
seed: "#FFF316"
font_family: Lato
day:
  background: "#fffffae2"
  error: "#ffba1a1a"
  error-container: "#ffffdad6"
  inverse-on-surface: "#fff6f1da"
  inverse-primary: "#ffd5cb00"
  inverse-surface: "#ff323121"
  on-background: "#ff1d1c0e"
  on-error: "#ffffffff"
  on-error-container: "#ff93000a"
  on-primary: "#ffffffff"
  on-primary-container: "#ff4c4800"
  on-secondary: "#ffffffff"
  on-secondary-container: "#ff444a22"
  on-surface: "#ff1d1c0e"
  on-surface-variant: "#ff494733"
  on-tertiary: "#ffffffff"
  on-tertiary-container: "#ff374d1d"
  outline: "#ff7b7861"
  outline-variant: "#ffcbc7ac"
  primary: "#ff666000"
  primary-container: "#fff3e700"
  secondary: "#ff5b6237"
  secondary-container: "#ffe0e7b1"
  surface: "#fffffae2"
  surface-bright: "#fffffae2"
  surface-container: "#fff3eed7"
  surface-container-high: "#ffede9d1"
  surface-container-highest: "#ffe7e3cc"
  surface-container-low: "#fff9f4dd"
  surface-container-lowest: "#ffffffff"
  surface-dim: "#ffdfdac4"
  surface-variant: "#ffe8e3c7"
  tertiary: "#ff4e6632"
  tertiary-container: "#ffcfecab"
night:
  background: "#ff151407"
  error: "#ffffb4ab"
  error-container: "#ff93000a"
  inverse-on-surface: "#ff323121"
  inverse-primary: "#ff666000"
  inverse-surface: "#ffe7e3cc"
  on-background: "#ffe7e3cc"
  on-error: "#ff690005"
  on-error-container: "#ffffdad6"
  on-primary: "#ff353200"
  on-primary-container: "#fff3e700"
  on-secondary: "#ff2d330d"
  on-secondary-container: "#ffe0e7b1"
  on-surface: "#ffe7e3cc"
  on-surface-variant: "#ffcbc7ac"
  on-tertiary: "#ff213608"
  on-tertiary-container: "#ffcfecab"
  outline: "#ff959179"
  outline-variant: "#ff494733"
  primary: "#ffd5cb00"
  primary-container: "#ff4c4800"
  secondary: "#ffc4cb97"
  secondary-container: "#ff444a22"
  surface: "#ff151407"
  surface-bright: "#ff3b3a2a"
  surface-container: "#ff212012"
  surface-container-high: "#ff2c2a1b"
  surface-container-highest: "#ff373526"
  surface-container-low: "#ff1d1c0e"
  surface-container-lowest: "#ff100f04"
  surface-dim: "#ff151407"
  surface-variant: "#ff494733"
  tertiary: "#ffb4d091"
  tertiary-container: "#ff374d1d"