id: ferns
name: Ferns
version: 2.0.0
source: companion
seed: "#003000"
font_family: Lato
day:
  background: "#fff4fceb"
  error: "#ffba1a1a"
  error-container: "#ffffdad6"
  inverse-on-surface: "#ffebf3e3"
  inverse-primary: "#ffe9c348"
  inverse-surface: "#ff2b3328"
  on-background: "#ff161e14"
  on-error: "#ffffffff"
  on-error-container: "#ff93000a"
  on-primary: "#ffffffff"
  on-primary-container: "#ff574500"
  on-secondary: "#ffffffff"
  on-secondary-container: "#ff574500"
  on-surface: "#ff161e14"
  on-surface-variant: "#ff3c4b37"
  on-tertiary: "#ffffffff"
  on-tertiary-container: "#ff285020"
  outline: "#ff6c7b65"
  outline-variant: "#ffbbcbb2"
  primary: "#ff735c00"
  primary-container: "#ffffe088"
  secondary: "#ff725c0c"
  secondary-container: "#ffffe088"
  surface: "#fff4fceb"
  surface-bright: "#fff4fceb"
  surface-container: "#ffe8f1e0"
  surface-container-high: "#ffe3ebda"
  surface-container-highest: "#ffdde5d5"
  surface-container-low: "#ffeef6e6"
  surface-container-lowest: "#ffffffff"
  surface-dim: "#ffd4ddcd"
  surface-variant: "#ffd7e8cd"
  tertiary: "#ff406836"
  tertiary-container: "#ffc0efb0"
night:
  background: "#ff0e150c"
  error: "#ffffb4ab"
  error-container: "#ff93000a"
  inverse-on-surface: "#ff2b3328"
  inverse-primary: "#ff735c00"
  inverse-surface: "#ffdde5d5"
  on-background: "#ffdde5d5"
  on-error: "#ff690005"
  on-error-container: "#ffffdad6"
  on-primary: "#ff3c2f00"
  on-primary-container: "#ffffe088"
  on-secondary: "#ff3c2f00"
  on-secondary-container: "#ffffe088"
  on-surface: "#ffdde5d5"
  on-surface-variant: "#ffbbcbb2"
  on-tertiary: "#ff11380b"
  on-tertiary-container: "#ffc0efb0"
  outline: "#ff86957e"
  outline-variant: "#ff3c4b37"
  primary: "#ffe9c348"
  primary-container: "#ff574500"
  secondary: "#ffe2c46d"
  secondary-container: "#ff574500"
  surface: "#ff0e150c"
  surface-bright: "#ff343b30"
  surface-container: "#ff1a2217"
  surface-container-high: "#ff252c21"
  surface-container-highest: "#ff2f372c"
  surface-container-low: "#ff161e14"
  surface-container-lowest: "#ff091007"
  surface-dim: "#ff0e150c"
  surface-variant: "#ff3c4b37"
  tertiary: "#ffa5d396"
  tertiary-container: "#ff285020"