id: colors
name: Colors
version: 2.0.0
source: companion
seed: "#E3FF00"
font_family: Lato
day:
  background: "#fff8fbec"
  error: "#ffba1a1a"
  error-container: "#ffffdad6"
  inverse-on-surface: "#ffeff2e3"
  inverse-primary: "#ffffb0ca"
  inverse-surface: "#ff2e3228"
  on-background: "#ff191d14"
  on-error: "#ffffffff"
  on-error-container: "#ff93000a"
  on-primary: "#ffffffff"
  on-primary-container: "#ff73304a"
  on-secondary: "#ffffffff"
  on-secondary-container: "#ff294e3b"
  on-surface: "#ff191d14"
  on-surface-variant: "#ff424939"
  on-tertiary: "#ffffffff"
  on-tertiary-container: "#ff314e22"
  outline: "#ff727a67"
  outline-variant: "#ffc2c9b4"
  primary: "#ff8f4762"
  primary-container: "#ffffd9e3"
  secondary: "#ff416652"
  secondary-container: "#ffc2ecd2"
  surface: "#fff8fbec"
  surface-bright: "#fff8fbec"
  surface-container: "#ffecf0e1"
  surface-container-high: "#ffe6eadb"
  surface-container-highest: "#ffe0e4d5"
  surface-container-low: "#fff2f5e6"
  surface-container-lowest: "#ffffffff"
  surface-dim: "#ffd8dccd"
  surface-variant: "#ffdee6cf"
  tertiary: "#ff486738"
  tertiary-container: "#ffc9edb2"
night:
  background: "#ff11150c"
  error: "#ffffb4ab"
  error-container: "#ff93000a"
  inverse-on-surface: "#ff2e3228"
  inverse-primary: "#ff8f4762"
  inverse-surface: "#ffe0e4d5"
  on-background: "#ffe0e4d5"
  on-error: "#ff690005"
  on-error-container: "#ffffdad6"
  on-primary: "#ff571934"
  on-primary-container: "#ffffd9e3"
  on-secondary: "#ff113726"
  on-secondary-container: "#ffc2ecd2"
  on-surface: "#ffe0e4d5"
  on-surface-variant: "#ffc2c9b4"
  on-tertiary: "#ff1b370d"
  on-tertiary-container: "#ffc9edb2"
  outline: "#ff8c9480"
  outline-variant: "#ff424939"
  primary: "#ffffb0ca"
  primary-container: "#ff73304a"
  secondary: "#ffa7d0b7"
  secondary-container: "#ff294e3b"
  surface: "#ff11150c"
  surface-bright: "#ff363b30"
  surface-container: "#ff1d2118"
  surface-container-high: "#ff272b22"
  surface-container-highest: "#ff32362c"
  surface-container-low: "#ff191d14"
  surface-container-lowest: "#ff0b0f07"
  surface-dim: "#ff11150c"
  surface-variant: "#ff424939"
  tertiary: "#ffadd198"
  tertiary-container: "#ff314e22"