id: default
name: Prodigy
version: 2.0.0
source: companion
seed: "#5050F8"
font_family: Lato
day:
  background: "#fffcf8ff"
  error: "#ffba1a1a"
  error-container: "#ffffdad6"
  inverse-on-surface: "#fff2effe"
  inverse-primary: "#ffc1c1ff"
  inverse-surface: "#ff302f3a"
  on-background: "#ff1b1b25"
  on-error: "#ffffffff"
  on-error-container: "#ff93000a"
  on-primary: "#ffffffff"
  on-primary-container: "#ff1e00ea"
  on-secondary: "#ffffffff"
  on-secondary-container: "#ff4b4163"
  on-surface: "#ff1b1b25"
  on-surface-variant: "#ff464554"
  on-tertiary: "#ffffffff"
  on-tertiary-container: "#ff573c69"
  outline: "#ff777585"
  outline-variant: "#ffc7c5d6"
  primary: "#ff3e3aff"
  primary-container: "#ffe1dfff"
  secondary: "#ff63597c"
  secondary-container: "#ffe9ddff"
  surface: "#fffcf8ff"
  surface-bright: "#fffcf8ff"
  surface-container: "#ffefecfb"
  surface-container-high: "#ffe9e6f5"
  surface-container-highest: "#ffe3e1ef"
  surface-container-low: "#fff5f2ff"
  surface-container-lowest: "#ffffffff"
  surface-dim: "#ffdbd8e7"
  surface-variant: "#ffe3e0f2"
  tertiary: "#ff705382"
  tertiary-container: "#fff3daff"
night:
  background: "#ff12121c"
  error: "#ffffb4ab"
  error-container: "#ff93000a"
  inverse-on-surface: "#ff302f3a"
  inverse-primary: "#ff3e3aff"
  inverse-surface: "#ffe3e1ef"
  on-background: "#ffe3e1ef"
  on-error: "#ff690005"
  on-error-container: "#ffffdad6"
  on-primary: "#ff1200a9"
  on-primary-container: "#ffe1dfff"
  on-secondary: "#ff342b4b"
  on-secondary-container: "#ffe9ddff"
  on-surface: "#ffe3e1ef"
  on-surface-variant: "#ffc7c5d6"
  on-tertiary: "#ff3f2551"
  on-tertiary-container: "#fff3daff"
  outline: "#ff908f9f"
  outline-variant: "#ff464554"
  primary: "#ffc1c1ff"
  primary-container: "#ff1e00ea"
  secondary: "#ffcdc0e8"
  secondary-container: "#ff4b4163"
  surface: "#ff12121c"
  surface-bright: "#ff383843"
  surface-container: "#ff1f1f29"
  surface-container-high: "#ff292934"
  surface-container-highest: "#ff34343f"
  surface-container-low: "#ff1b1b25"
  surface-container-lowest: "#ff0d0d17"
  surface-dim: "#ff12121c"
  surface-variant: "#ff464554"
  tertiary: "#ffddbaf0"
  tertiary-container: "#ff573c69"