id: default
name: Prodigy
version: 2.0.0
source: companion
seed: "#5050F8"
font_family: Lato
day:
  background: "#fffcf8ff"
  error: "#ffba1a1a"
  error-container: "#ffffdad6"
  inverse-on-surface: "#fff2effd"
  inverse-primary: "#ffc1c1ff"
  inverse-surface: "#ff302f3a"
  on-background: "#ff1b1b24"
  on-error: "#ffffffff"
  on-error-container: "#ff93000a"
  on-primary: "#ffffffff"
  on-primary-container: "#ffeae8ff"
  on-secondary: "#ffffffff"
  on-secondary-container: "#ff3b3d86"
  on-surface: "#ff1b1b24"
  on-surface-variant: "#ff464556"
  on-tertiary: "#ffffffff"
  on-tertiary-container: "#ffffe1fa"
  outline: "#ff767587"
  outline-variant: "#ffc6c4d9"
  primary: "#ff3531e0"
  primary-container: "#ff5050f8"
  secondary: "#ff5557a1"
  secondary-container: "#ffaaacfe"
  surface: "#fffcf8ff"
  surface-bright: "#fffcf8ff"
  surface-container: "#ffefecfa"
  surface-container-high: "#ffe9e6f4"
  surface-container-highest: "#ffe4e1ee"
  surface-container-low: "#fff5f2ff"
  surface-container-lowest: "#ffffffff"
  surface-dim: "#ffdbd8e6"
  surface-variant: "#ffe3e0f5"
  tertiary: "#ff8e029d"
  tertiary-container: "#ffab2fb8"
night:
  background: "#ff12131c"
  error: "#ffffb4ab"
  error-container: "#ff93000a"
  inverse-on-surface: "#ff302f3a"
  inverse-primary: "#ff4442ed"
  inverse-surface: "#ffe4e1ee"
  on-background: "#ffe4e1ee"
  on-error: "#ff690005"
  on-error-container: "#ffffdad6"
  on-primary: "#ff1200a9"
  on-primary-container: "#ffeae8ff"
  on-secondary: "#ff262670"
  on-secondary-container: "#ffacaeff"
  on-surface: "#ffe4e1ee"
  on-surface-variant: "#ffc6c4d9"
  on-tertiary: "#ff590062"
  on-tertiary-container: "#ffffe1fa"
  outline: "#ff908fa2"
  outline-variant: "#ff464556"
  primary: "#ffc1c1ff"
  primary-container: "#ff5050f8"
  secondary: "#ffc1c1ff"
  secondary-container: "#ff3d3e88"
  surface: "#ff12131c"
  surface-bright: "#ff393843"
  surface-container: "#ff1f1f28"
  surface-container-high: "#ff292933"
  surface-container-highest: "#ff34343e"
  surface-container-low: "#ff1b1b24"
  surface-container-lowest: "#ff0d0d16"
  surface-dim: "#ff12131c"
  surface-variant: "#ff464556"
  tertiary: "#fffea9ff"
  tertiary-container: "#ffab2fb8"