id: leather
name: Leather
version: 2.0.0
source: companion
seed: "#101010"
font_family: Lato
day:
  background: "#fffaf9f9"
  error: "#ffba1a1a"
  error-container: "#ffffdad6"
  inverse-on-surface: "#fff2f0f0"
  inverse-primary: "#ffb8cacd"
  inverse-surface: "#ff2f3031"
  on-background: "#ff1b1c1c"
  on-error: "#ffffffff"
  on-error-container: "#ff93000a"
  on-primary: "#ffffffff"
  on-primary-container: "#ff39494c"
  on-secondary: "#ffffffff"
  on-secondary-container: "#ff3f484a"
  on-surface: "#ff1b1c1c"
  on-surface-variant: "#ff464747"
  on-tertiary: "#ffffffff"
  on-tertiary-container: "#ff334b4f"
  outline: "#ff777777"
  outline-variant: "#ffc7c6c6"
  primary: "#ff516164"
  primary-container: "#ffd4e6e9"
  secondary: "#ff576062"
  secondary-container: "#ffdbe4e6"
  surface: "#fffaf9f9"
  surface-bright: "#fffaf9f9"
  surface-container: "#ffefeded"
  surface-container-high: "#ffe9e8e8"
  surface-container-highest: "#ffe3e2e2"
  surface-container-low: "#fff4f3f3"
  surface-container-lowest: "#ffffffff"
  surface-dim: "#ffdbdad9"
  surface-variant: "#ffe3e2e2"
  tertiary: "#ff4a6267"
  tertiary-container: "#ffcde7ec"
night:
  background: "#ff121414"
  error: "#ffffb4ab"
  error-container: "#ff93000a"
  inverse-on-surface: "#ff2f3031"
  inverse-primary: "#ff516164"
  inverse-surface: "#ffe3e2e2"
  on-background: "#ffe3e2e2"
  on-error: "#ff690005"
  on-error-container: "#ffffdad6"
  on-primary: "#ff233336"
  on-primary-container: "#ffd4e6e9"
  on-secondary: "#ff293234"
  on-secondary-container: "#ffdbe4e6"
  on-surface: "#ffe3e2e2"
  on-surface-variant: "#ffc7c6c6"
  on-tertiary: "#ff1c3438"
  on-tertiary-container: "#ffcde7ec"
  outline: "#ff919191"
  outline-variant: "#ff464747"
  primary: "#ffb8cacd"
  primary-container: "#ff39494c"
  secondary: "#ffbfc8ca"
  secondary-container: "#ff3f484a"
  surface: "#ff121414"
  surface-bright: "#ff383939"
  surface-container: "#ff1f2020"
  surface-container-high: "#ff292a2a"
  surface-container-highest: "#ff343535"
  surface-container-low: "#ff1b1c1c"
  surface-container-lowest: "#ff0d0e0f"
  surface-dim: "#ff121414"
  surface-variant: "#ff464747"
  tertiary: "#ffb1cbd0"
  tertiary-container: "#ff334b4f"